### ISSUE TITLE
logging in upon setup (when using yuno credentials) results in 401 error

### ISSUE THREAD

**Issue by S4GU4R0** [k0a1a/hotglue_ynh#4]
Hey there, I can't figure out how to log in once installing the app. I have the setting to use Yunohost SSO turned on, but I get a 401 error when I use those credentials. I am not sure which other ones to use, since I just installed it and haven't done anything else yet.

**Comment by isAAAc** [comment]
same error here
VPS deb12
```
root@krashboyz:~# yunohost --version
yunohost: 
  repo: stable
  version: 12.0.12
yunohost-admin: 
  repo: stable
  version: 12.0.7
yunohost-portal: 
  repo: stable
  version: 12.0.10
moulinette: 
  repo: stable
  version: 12.0.4
ssowat: 
  repo: stable
  version: 12.0.3

root@krashboyz:~# yunohost app info hotglue 
description: Content manipulation system for building websites
domain_path: test.krashboyz.org/
name: Hotglue
version: 1.04~ynh2
```
```
nginx access log:

2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:19 +0100] "GET /js/jquery-1.5.2.min.js HTTP/2.0" 304 0 "https://test.krashboyz.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:19 +0100] "GET /js/glue.min.js HTTP/2.0" 304 0 "https://test.krashboyz.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:19 +0100] "GET /js/create_page.min.js HTTP/2.0" 304 0 "https://test.krashboyz.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:19 +0100] "GET /img/favicon.ico HTTP/2.0" 304 0 "https://test.krashboyz.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:20 +0100] "POST /json.php HTTP/2.0" 401 1131 "https://test.krashboyz.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:52 +0100] "GET / HTTP/2.0" 200 1819 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
2001:67c:288:2::235 - isaaac [24/Mar/2025:19:11:53 +0100] "POST /json.php HTTP/2.0" 401 1131 "https://test.krashboyz.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
```
